export const projects = [
  {
    title: "Motion Study",
    image: "/img1.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.2,
  },
  {
    title: "Idle Form",
    image: "/img2.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 0.8,
  },
  {
    title: "Blur Signal",
    image: "/img3.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.4,
  },
  {
    title: "Still Drift",
    image: "/img4.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 0.9,
  },
  {
    title: "Tidewalk",
    image: "/img5.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.1,
  },
  {
    title: "Core Motion",
    image: "/img6.jpeg",
    year: 2022,
    href: "/sample-project",
    size: 0.7,
  },
  {
    title: "White Bloom",
    image: "/img7.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.3,
  },
  {
    title: "Backrun",
    image: "/img8.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 0.6,
  },
  {
    title: "Rushline",
    image: "/img9.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.0,
  },
  {
    title: "Afterimage",
    image: "/img10.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 1.5,
  },
  {
    title: "Shadowhead",
    image: "/img11.jpeg",
    year: 2022,
    href: "/sample-project",
    size: 0.8,
  },
  {
    title: "Opal Lace",
    image: "/img12.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.1,
  },
  {
    title: "Glassprint",
    image: "/img13.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 0.9,
  },
  {
    title: "Redshift",
    image: "/img14.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 1.2,
  },
  {
    title: "White Noise",
    image: "/img15.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 0.7,
  },
  {
    title: "Twin Field",
    image: "/img16.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.4,
  },
  {
    title: "Petalloop",
    image: "/img17.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 0.8,
  },
  {
    title: "Ghostwalk",
    image: "/img18.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.0,
  },
  {
    title: "Heatwave",
    image: "/img19.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 1.3,
  },
  {
    title: "Sky Drift",
    image: "/img20.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 0.9,
  },
  {
    title: "Spindle",
    image: "/img21.jpeg",
    year: 2022,
    href: "/sample-project",
    size: 1.1,
  },
  {
    title: "Pacer",
    image: "/img22.jpeg",
    year: 2023,
    href: "/sample-project",
    size: 0.6,
  },
  {
    title: "Stride",
    image: "/img23.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.2,
  },
  {
    title: "Cryo Pulse",
    image: "/img24.jpeg",
    year: 2022,
    href: "/sample-project",
    size: 0.8,
  },
  {
    title: "Velvet Blur",
    image: "/img25.jpeg",
    year: 2024,
    href: "/sample-project",
    size: 1.5,
  },
];
